Add and remove functions to the APP
AlierPM/To-Do-List pull request #2
Opened 2022-08-20 21:59 UTC by AlierPM

# In this project, the following changes have been effected:

* A user can add a new task
* A user can delete a task
* A user can edit a task
* Deleting a task updates all remaining items' indexes
* All changes to the To Do List are saved in local storage

2022-08-20 22:09 UTC, MeqdamAlqudah requested changes
Hi @AlierPM , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media2.giphy.com/media/qLWdMYX1NYF2g/200w.webp?cid=ecf05e47d060v5mh4njf0d2yrxy66tilkklg1czcunui42r3&rid=200w.webp&ct=g)

 ## Highlights
:+1: Readme File

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 22:09 UTC, MeqdamAlqudah commented on src/index.html
> +		<link rel="preconnect" href="https://fonts.googleapis.com">
- [ ] Please make sure that checking item as completed is saved in the localStorage.
![image](https://user-images.githubusercontent.com/74744787/185767565-f90f80a6-c5db-484b-8234-c2a0f0692a0b.png)

2022-08-20 22:09 UTC, MeqdamAlqudah commented on src/index.html
> +		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
- [  ]  Please I can see that the user can edit a task but the issue is when the user edits two tasks a weird behavior happen one of the edited tasks seems to override editing the other one please fix this issue
![image](https://user-images.githubusercontent.com/74744787/185767612-a4f165e4-7607-4b83-bfae-dc631c5c0991.png)

2022-08-20 22:09 UTC, MeqdamAlqudah commented on src/index.html
> +		<link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap" rel="stylesheet">
- [ ] Please make sure to fix this linter error
![image](https://user-images.githubusercontent.com/74744787/185767638-d304236b-db13-43a5-959f-d1f3fc80f605.png)

2022-08-20 23:09 UTC, Munsa1 approved these changes
Hi @AlierPM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions
- [ ] It would improve the user experience if the task caan be renamed by clicking on the text.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 23:40 UTC, rloterh requested changes
Hi Alier, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._


<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 23:40 UTC, rloterh commented on src/modules/removeTask.js
> +    taskArray = taskArray.filter((task) => !task.completed);
- [ ] Checking a task as completed does not change the corresponding task value of the local storage. Kindly ensure that checking a task as completed changes the value of that task from `false` to `true`, as informed in the previous review

2022-08-20 23:40 UTC, rloterh commented on src/modules/editTask.js
> +const editTask = (id) => {
- [ ] Editing a task overrides the previous task, and task 2 rather gets edited in the local storage. Kindly ensure that the appropriate task edited reflects on the both the frontend and the in the corresponding local storage

**Before Editing First task `one`:**
![image](https://user-images.githubusercontent.com/12745474/185769419-eb59ad7a-3bf0-4253-8d7d-6257ddee7569.png)


**After Editing First take `one`:**
![image](https://user-images.githubusercontent.com/12745474/185769457-94ec91ac-f4e3-4320-ba85-6ad8c2b77c75.png)

2022-08-22 16:32 UTC, ShahierNashaat approved these changes
Hi @AlierPM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 16:33 UTC, merged